<?php
$video_embed_style = new stdClass();
$video_embed_style->disabled = FALSE; /* Edit this to true to make a default video_embed_style disabled initially */
$video_embed_style->api_version = 1;
$video_embed_style->name = 'video_43_400';
$video_embed_style->title = 'video_43_400';
$video_embed_style->data = array(
  'youtube' => array(
    'width' => '400',
    'height' => '300',
    'theme' => 'dark',
    'autoplay' => 0,
    'vq' => 'large',
    'rel' => 0,
    'showinfo' => 0,
    'modestbranding' => 0,
    'iv_load_policy' => '1',
    'controls' => '1',
    'autohide' => '2',
  ),
  'vimeo' => array(
    'width' => '640',
    'height' => '360',
    'color' => '00adef',
    'portrait' => 1,
    'title' => 1,
    'byline' => 1,
    'autoplay' => 0,
    'loop' => 0,
    'froogaloop' => 0,
  ),
  'data__active_tab' => 'edit-data-youtube',
);
