<?php
/**
 * @file
 * Provides a province list for Portales7 AEMET module
 */
function _portales7_aemet_get_provincias() {
  return array(
    0 => t('Choose province'),
    'Andalucía' => array(
      4 => 'Almería',
      11 => 'Cádiz',
      14 => 'Córdoba',
      18 => 'Granada',
      21 => 'Huelva',
      23 => 'Jaén',
      29 => 'Málaga',
      41 => 'Sevilla',
    ),
    'Aragón' => array(
      22 => 'Huesca',
      44 => 'Teruel',
      50 => 'Zaragoza',
    ),
    33 => 'Asturias',
    7 => 'Illes Balears',
    'Islas Canarias' => array(
      35 => 'Las Palmas',
      38 => 'Santa Cruz de Tenerife',
    ),
    39 => 'Cantabria',
    'Catalunya' => array(
      8 => 'Barcelona',
      17 => 'Girona',
      25 => 'Lleida',
      43 => 'Tarragona',
    ),
    'Castilla y León' => array(
      5 => 'Ávila',
      9 => 'Burgos',
      24 => 'León',
      34 => 'Palencia',
      37 => 'Salamanca',
      40 => 'Segovia',
      42 => 'Soria',
      47 => 'Valladolid',
      49 => 'Zamora',
    ),
    'Castilla la Mancha' => array(
      2 => 'Albacete',
      13 => 'Ciudad Real',
      16 => 'Cuenca',
      19 => 'Guadalajara',
      45 => 'Toledo',
    ),
    51 => 'Ceuta',
    'Euskadi' => array(
      1 => 'Álava',
      20 => 'Guipúzcoa',
      48 => 'Vizcaya',
    ),
    'Extremadura' => array(
      6 => 'Badajoz',
      10 => 'Cáceres',
    ),
    'Galicia' => array(
      15 => 'A Coruña',
      27 => 'Lugo',
      32 => 'Ourense',
      36 => 'Pontevedra',
    ),
    28 => 'Madrid',
    52 => 'Melilla',
    30 => 'Murcia',
    31 => 'Navarra',
    26 => 'La Rioja',
    'Comunitat Valenciana' => array(
      3 => 'Alicante',
      12 => 'Castellón',
      46 => 'Valencia',
    ),
  );
}

