<?php
$view_modes = array(
  'teaser' => array(
    'label' => 'Resumen',
    'custom_settings' => TRUE,
  ),
  'titulo' => array(
    'label' => 'Titulo',
    'custom_settings' => TRUE,
  ),
  'link' => array(
    'label' => 'Enlace',
    'custom_settings' => TRUE,
  ),
  'lugar' => array(
    'label' => 'lugar',
    'custom_settings' => TRUE,
  ),
  'vinculo_agenda_resumen' => array(
    'label' => 'vinculo agenda resumen',
    'custom_settings' => TRUE,
  ),
  'vinculo_agenda_titular' => array(
    'label' => 'vinculo agenda titular',
    'custom_settings' => TRUE,
  ),
  'vinculo_archivo' => array(
    'label' => 'vinculo archivo',
    'custom_settings' => TRUE,
  ),
  'vinculo_escaparate_libre' => array(
    'label' => 'vinculo escaparate libre',
    'custom_settings' => TRUE,
  ),
  'vinculo_imagen_43_150' => array(
    'label' => 'vinculo medio principal 43-150',
    'custom_settings' => TRUE,
  ),
  'vinculo_imagen_adjunta_43_150' => array(
    'label' => 'vinculo imagen adjunta 43-150',
    'custom_settings' => TRUE,
  ),
  'vinculo_noticia_completo' => array(
    'label' => 'vinculo noticia completo',
    'custom_settings' => TRUE,
  ),
  'vinculo_noticia_resumen' => array(
    'label' => 'vinculo noticia resumen',
    'custom_settings' => TRUE,
  ),
  'vinculo_noticia_simple' => array(
    'label' => 'vinculo noticia simple',
    'custom_settings' => TRUE,
  ),
  'vinculo_noticia_titular' => array(
    'label' => 'vinculo noticia titular',
    'custom_settings' => TRUE,
  ),
);
