<?php
$extra_fields = array(
  'form' => array(),
  'display' => array(
    'language' => array(
      'default' => array(
        'weight' => 0,
        'visible' => FALSE,
      ),
      'vinculo_articulo_completo' => array(
        'weight' => 20,
        'visible' => FALSE,
      ),
      'vinculo_articulo_resumen' => array(
        'weight' => 4,
        'visible' => FALSE,
      ),
      'vinculo_articulo_simple' => array(
        'weight' => 20,
        'visible' => FALSE,
      ),
      'vinculo_articulo_titular' => array(
        'weight' => 12,
        'visible' => FALSE,
      ),
      'vinculo_noticia_completo' => array(
        'weight' => 20,
        'visible' => FALSE,
      ),
      'vinculo_noticia_simple' => array(
        'weight' => 12,
        'visible' => FALSE,
      ),
      'vinculo_noticia_titular' => array(
        'weight' => 18,
        'visible' => FALSE,
      ),
      'vinculo_elemento_completo' => array(
        'weight' => 13,
        'visible' => FALSE,
      ),
      'vinculo_elemento_resumen' => array(
        'weight' => 20,
        'visible' => FALSE,
      ),
      'vinculo_elemento_titular' => array(
        'weight' => 1,
        'visible' => FALSE,
      ),
      'vinculo_escaparate_completo' => array(
        'weight' => 5,
        'visible' => FALSE,
      ),
      'vinculo_escaparate_libre' => array(
        'weight' => 20,
        'visible' => FALSE,
      ),
      'vinculo_escaparate_resumen' => array(
        'weight' => 4,
        'visible' => FALSE,
      ),
      'vinculo_escaparate_simple' => array(
        'weight' => 2,
        'visible' => FALSE,
      ),
      'vinculo_noticia_resumen' => array(
        'weight' => 20,
        'visible' => FALSE,
      ),
      'bim' => array(
        'weight' => 21,
        'visible' => FALSE,
      ),
      'listado_resumen' => array(
        'weight' => 20,
        'visible' => FALSE,
      ),
      'listado_completo' => array(
        'weight' => 0,
        'visible' => FALSE,
      ),
      'lugar' => array(
        'weight' => 11,
        'visible' => FALSE,
      ),
      'link' => array(
        'weight' => 2,
        'visible' => FALSE,
      ),
      'portales7_entity_person' => array(
        'weight' => 0,
        'visible' => FALSE,
      ),
      'portales7_entity_building' => array(
        'weight' => 9,
        'visible' => FALSE,
      ),
      'logo_title' => array(
        'weight' => 0,
        'visible' => FALSE,
      ),
      'vinculo_imagen_43_150' => array(
        'weight' => 24,
        'visible' => FALSE,
      ),
      'vinculo_imagen_43_200' => array(
        'weight' => 9,
        'visible' => FALSE,
      ),
      'vinculo_imagen_adjunta_43_150' => array(
        'weight' => 25,
        'visible' => FALSE,
      ),
      'vinculo_imagen_adjunta_43_200' => array(
        'weight' => 8,
        'visible' => FALSE,
      ),
      'vinculo_archivo' => array(
        'weight' => 25,
        'visible' => FALSE,
      ),
      'carrusel_ediciones' => array(
        'weight' => 20,
        'visible' => FALSE,
      ),
      'teaser' => array(
        'weight' => 3,
        'visible' => FALSE,
      ),
    ),
  ),
);